/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 83ebb942bf9c5d890445259a62a0fdb5)
interface __BaseEnv_Env {
  FUNNEL: AnalyticsEngineDataset
  ASSETS: Fetcher
  ANALYTICS_ENABLED: 'false' | 'true'
  APP_ORIGIN:
    'https://staging.stravastitch.com' | 'https://stravastitch.com' | 'http://localhost:44100'
  STRAVA_CLIENT_ID: '262735'
  STRAVA_WEBHOOK_SUBSCRIPTION_ID: '' | '371550'
  STRAVA_CLIENT_SECRET: string
  SESSION_SECRET: string
  TOKEN_ENCRYPTION_KEY: string
  STRAVA_WEBHOOK_VERIFY_TOKEN: string
  ATHLETES: DurableObjectNamespace<import('./worker').AthleteData>
  SESSIONS: DurableObjectNamespace<import('./worker').BrowserSession>
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker')
    durableNamespaces: 'AthleteData' | 'BrowserSession'
  }
  interface StagingEnv {
    FUNNEL: AnalyticsEngineDataset
    ASSETS: Fetcher
    ANALYTICS_ENABLED: 'false'
    APP_ORIGIN: 'https://staging.stravastitch.com'
    STRAVA_CLIENT_ID: '262735'
    STRAVA_WEBHOOK_SUBSCRIPTION_ID: ''
    STRAVA_CLIENT_SECRET: string
    SESSION_SECRET: string
    TOKEN_ENCRYPTION_KEY: string
    STRAVA_WEBHOOK_VERIFY_TOKEN: string
    ATHLETES: DurableObjectNamespace<import('./worker').AthleteData>
    SESSIONS: DurableObjectNamespace<import('./worker').BrowserSession>
  }
  interface ProductionEnv {
    FUNNEL: AnalyticsEngineDataset
    ASSETS: Fetcher
    ANALYTICS_ENABLED: 'true'
    APP_ORIGIN: 'https://stravastitch.com'
    STRAVA_CLIENT_ID: '262735'
    STRAVA_WEBHOOK_SUBSCRIPTION_ID: '371550'
    STRAVA_CLIENT_SECRET: string
    SESSION_SECRET: string
    TOKEN_ENCRYPTION_KEY: string
    STRAVA_WEBHOOK_VERIFY_TOKEN: string
    ATHLETES: DurableObjectNamespace<import('./worker').AthleteData>
    SESSIONS: DurableObjectNamespace<import('./worker').BrowserSession>
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ANALYTICS_ENABLED'
      | 'APP_ORIGIN'
      | 'STRAVA_CLIENT_ID'
      | 'STRAVA_WEBHOOK_SUBSCRIPTION_ID'
      | 'STRAVA_CLIENT_SECRET'
      | 'SESSION_SECRET'
      | 'TOKEN_ENCRYPTION_KEY'
      | 'STRAVA_WEBHOOK_VERIFY_TOKEN'
    >
  > {}
}
